name: PerchHomeGUI
version: 1.0.0
main: me.perch.homegui.Homegui
api-version: 1.13
depend: [Essentials]
authors: [TechnoVision, KayaLambrex]
commands:
  home:
    description: Opens the HomeGUI screen.
    usage: /<command>
    aliases: [homes, h]